pipeline {
    agent {
        docker {
            image 'maven:3.6.2'
            args '-v /root/.m2:/root/.m2'
        }
    }
	environment {
		PATH= '/usr/sbin:/usr/bin:/sbin:/bin:$PATH'
	}
    stages {
		stage('Echo') {
            steps {
               echo "PATH is: $PATH"
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
